server:
  port: 8888

spring:
  application:
    name: config

zoho:
  api:
    token-base-url: ${ZOHO_TOKEN_BASE_URL}
    client-id: ${ZOHO_CLIENT_ID}
    client-secret: ${ZOHO_CLIENT_SECRET}
    refresh-token: ${ZOHO_REFRESH_TOKEN}

logging:
  level:
    com.smartscheduler: INFO