
server:
  port: 8083
spring:
  application:
    name: notification

management:
  endpoints:
    web:
      exposure:
        include: health,info

notification:
  scheduling:
    response-window-minutes: 3
    max-consecutive-misses: 3
    opt-out-duration: PT15M

  patient:
    priority:
      engine: ${NOTIFICATION_PATIENT_PRIORITY_ENGINE}
      weights:
        is-vip: 0.3
        severity-level: 0.25
        acceptance-rate: 0.25
        time-difference: 0.1
        time-consistency-std-dev: 0.1

