
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/user/**
            - id: appointment
              uri: lb://appointment
              predicates:
                - Path=/appointment/**
            - id: notification
              uri: lb://notification
              predicates:
                - Path=/notification/**
            - id: audit
              uri: lb://audit
              predicates:
                - Path=/audit/**
