server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: appointment
              uri: lb://appointment
              predicates:
                - Path=/api/v1/appointment/**
            - id: notification
              uri: lb://notification
              predicates:
                - Path=/api/v1/notification/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    gateway:
      access: unrestricted
