
server:
  port: 9999

spring:
  application:
    name: demo
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

message:
  system-phone: 919999999999