package com.smartscheduler.notification.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@ConditionalOnProperty(name = "message.provider", havingValue = "demo")
@RequiredArgsConstructor
public class SimulatedWhatsAppMessageService implements MessageService {

    private static final Logger log = LoggerFactory.getLogger(SimulatedWhatsAppMessageService.class);

    @Value("${message.system-phone}")
    private String systemPhone;

    private final RestTemplate restTemplate;
    // Jackson ObjectMapper is injected to handle conversion from Java objects (Map/List) to JSON string
    private final ObjectMapper objectMapper;

    @Override
    public void sendWhatsAppMessage(List<Map<String, Object>> messages) {
        if (messages == null || messages.isEmpty()) {
            log.warn("No messages to send");
            return;
        }

        final String baseUrl = "http://localhost:9999/demo/chat/external";

        for (Map<String, Object> msg : messages) {
            try {
                String recipientId = (String) msg.get("recipient_id");
                String text = (String) msg.get("text");
                // The buttons structure is derived from Rasa's output
                List<Map<String, Object>> buttons = (List<Map<String, Object>>) msg.get("buttons");

                HttpHeaders headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);

                // buildPayload now returns the entire JSON structure as a String, generated by ObjectMapper
                String payloadJson = buildPayload(recipientId, text, buttons);

                HttpEntity<String> request = new HttpEntity<>(payloadJson, headers);
                ResponseEntity<String> response = restTemplate.postForEntity(baseUrl, request, String.class);

                log.info("✅ Demo WhatsApp message sent to [{}], status={}, response={}",
                        recipientId, response.getStatusCode(), response.getBody());

            } catch (JsonProcessingException e) {
                log.error("❌ Failed to serialize payload for Demo WhatsApp message", e);
            } catch (Exception e) {
                log.error("❌ Failed to send Demo WhatsApp message", e);
            }
        }
    }

    /**
     * Builds the JSON payload for the external demo chat service using Java Map/List objects,
     * which are then converted to a JSON string using ObjectMapper.
     * This ensures correct structure and escaping, treating all JSON components as objects.
     * The 'to' field uses the raw recipientId to match the local demo endpoint's requirement.
     */
    private String buildPayload(String recipientId, String text, List<Map<String, Object>> buttons) throws JsonProcessingException {
        // Use a LinkedHashMap to maintain insertion order (for cleaner JSON output)
        Map<String, Object> payload = new LinkedHashMap<>();

        // The 'from' field is always prefixed with whatsapp:+
        payload.put("from", "whatsapp:+" + systemPhone);

        // --- 1. Handle Interactive Message (with buttons) ---
        if (buttons != null && !buttons.isEmpty()) {

            // Map the Rasa buttons to the required interactive button structure
            List<Map<String, Object>> interactiveButtons = new ArrayList<>();
            for (Map<String, Object> btn : buttons) {

                // Get payload, remove leading '/'
                String payloadId = ((String) btn.get("payload")).replace("/", "");
                String buttonTitle = (String) btn.get("title");

                // Create the reply object: {"id":"%s","title":"%s"}
                Map<String, Object> reply = Map.of(
                        "id", payloadId,
                        "title", buttonTitle
                );

                // Create the button object: {"type":"reply","reply":{...}}
                Map<String, Object> interactiveButton = Map.of(
                        "type", "reply",
                        "reply", reply
                );

                interactiveButtons.add(interactiveButton);
            }

            // Construct nested interactive structure
            Map<String, Object> action = Map.of("buttons", interactiveButtons);
            Map<String, Object> body = Map.of("text", text);
            Map<String, Object> interactive = Map.of(
                    "type", "button",
                    "body", body,
                    "action", action
            );

            // Populate top-level payload fields for interactive message
            // Uses raw recipientId to match the user's required curl payload structure
            payload.put("to", "whatsapp:+" + recipientId);
            payload.put("type", "interactive");
            payload.put("interactive", interactive);

        }

        // --- 2. Handle Simple Text Message (no buttons) ---
        else {
            // Populate top-level payload fields for simple text message
            // Set 'to' using raw recipientId for consistency with the interactive message structure
            payload.put("to", "whatsapp:+" + recipientId);
            payload.put("body", text);
        }

        // Convert the complete Java object structure to a final, correctly escaped JSON string
        return objectMapper.writeValueAsString(payload);
    }
}
